# Base configs
baseurl: "https://learningdotnet17.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photos by Brijesh Chawla"
subtitle: "Cameras: Canon 6D, Fuji X-T1"
author: "Brijesh Chawla"
header:
 title: "Photos"
 subtitle: "by Brijesh Chawla"
footer:
 name: ""
 bio: ""
 github: "Site Credit: <a href=\"https://github.com/ramswaroop/photography\">Ram Patar</a>"
web_design: ""
social_urls:
  instagram: "https://www.instagram.com/brijeshchawla17"
